### PR TITLE
YAML sample for OpenShift Console

### PR DESCRIPTION
**Pull request by zregvart**
Ref. https://issues.redhat.com/browse/HACBS-2066

### CODE REVIEW

**Review by lcarva — APPROVED** [review]
Cool! 

I'm not too familiar with `ConsoleYAMLSample`. How does that work in OpenShift?

**Comment by zregvart** [comment]
I'll provide some screenshots or demo this...

**Comment by zregvart** [comment]
Here is a quick demo of this:

[Screencast from 2023-04-28 12-24-46.webm](https://user-images.githubusercontent.com/1306050/235123606-09f77fe9-6148-4090-b990-1ed0091d1a55.webm)

**Comment by lcarva** [comment]
Nice!

**Pull request merged**
